---
title: "About"
---

These materials are developed as part of the Wikimedia Research project [*Wikimedia at Summer Institutes in Computational Social Science*](https://meta.wikimedia.org/wiki/Research:Wikimedia_at_Summer_Institutes_in_Computational_Social_Science).

These materials were made to provide a half-day, hands-on learning session on accessing data from Wikipedia during the SICSS events in Kenya, Nigeria and Burkina Faso in 2026, following a half-day more general introduction into what Wikipedia/Wikimedia is and what types of research those data can enable. 

## Re-use and licenses

We want you to re-use and adapt these materials for your own teaching as much as possible.
For this reason, they are dual licensed, depending on the content type:

* These teaching materials themselves are openly licensed [under the *Creative Commons Attribution-Share Alike 4.0* (CC BY-SA 4.0) license](https://creativecommons.org/licenses/by-sa/4.0/). This means you can use, remix and republish those materials as long as they are under the same license and co-attribute us.
* All the code for accessing and analysing the the Wiki data that is part of these materials is [released into the public domain using the *Creative Commons Zero* Deed (CC 0)](https://creativecommons.org/publicdomain/zero/1.0/). This means you can re-use and adapt the code in any way you want - without any requirements attached.

### Translations

We would love these materials to exist in more languages. If you translate them to teach using them in your own language context, please consider [contributing the materials back to us via GitHub](https://github.com/citizensandtech/sicss-wikipedia).

## Authors

### Dr. Bastian Greshake Tzovaras

web: [https://tzovar.as/](https://tzovar.as/) | mastodon: [@gedankenstuecke@scholar.social](https://scholar.social/@gedankenstuecke/)

Bastian (he/him) is an interdisciplinary researcher working on the theory and practice of co-created participatory science and peer production. His work intersects with open source/science technologies and how they can be in service of individuals & communities that want to engage in knowledge production, bringing together applied and theoretical methods from computer/data science, human-computer-interaction and critical science & technology studies.

Bastian’s prior academic postings include being a senior researcher at the Alan Turing Institute in London and being the team-lead of the Peer-Produced Research Lab as part of an INSERM unit at Université Paris Cité. His academic journey started in biology/bioinformatics, with a PhD on how symbiotic relationships influence genomic evolution. 

In the realm of participatory science, he was the co-founder and lead of openSNP, a crowdsourced/citizen science open data project that ran between 2011-2025. Since 2017, he also acts as the Director of Research for Open Humans – a non-profit that provides digital & social infrastructures for individual & community-driven citizen science and self-research. 

### Psyche Wanqing He

web:[https://psychehe.github.io](https://psychehe.github.io)| email:[wh385@cornell.edu](wh385@cornell.edu)

Psyche (she/her) is a cognitive scientist working at the intersection of human-AI interaction, psycholinguistics, and computational social science. Her research examines how AI is reshaping the way people communicate and connect with each other via conversation. She pairs applied and theoretical methods from cognitive psychology, NLP, and HCI, combining large-scale corpus and computational analysis with controlled human-subjects experiments and field studies.

Psyche’s academic journey started in linguistics and psychology during her undergraduate training at UC Berkeley. She is completing her PhD in Information Science at Cornell University advised by Susan R. Fussell, following doctoral training in psychology and a minor in cognitive science. Her research shows how virtual settings disadvantages communication fluency, especially for speakers lack of language proficiency and domain expertise, and how just-in-time personalized AI mediation can effectively bridge such barriers to restore communication smoothness and confidence. In 2024, she founded XPLAIN, a proactive AI scaffold that supports non-native speakers in real-time online meetings, through Cornell's Entrepreneurship Lab startup accelerator. 
