<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr">
<head>
<link rel="alternate" hreflang="en" href="https://citizensandtech.github.io/sicss-wikipedia/02-pywikibot.html" />
<link rel="alternate" hreflang="fr" href="https://citizensandtech.github.io/sicss-wikipedia/fr/02-pywikibot.fr.html" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Accessing data from Wiki projects – SICSS : Utilisation de Wikipédia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script><script src="site_libs/quarto-nav/headroom.min.js"></script><script src="site_libs/clipboard/clipboard.min.js"></script><script src="site_libs/quarto-search/autocomplete.umd.js"></script><script src="site_libs/quarto-search/fuse.min.js"></script><script src="site_libs/quarto-search/quarto-search.js"></script><meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script><script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script><script src="site_libs/quarto-html/popper.min.js"></script><script src="site_libs/quarto-html/tippy.umd.min.js"></script><script src="site_libs/quarto-html/anchor.min.js"></script><link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script><link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-73c880a72bf6022e65cfd02f19d274f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script><script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">SICSS : Utilisation de Wikipédia</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Recherche"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Basculer la navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item"><div class="dropdown" id="languages-links-parent">
<button class="btn btn-primary dropdown-toggle babelquarto-languages-button" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="languages-button"><i class="bi bi-globe2"></i> Français</button><ul class="dropdown-menu" id="languages-links"><li><a class="dropdown-item" href="https://citizensandtech.github.io/sicss-wikipedia/02-pywikibot.html" id="language-link-en">English</a></li></ul>
</div></li>
<li class="nav-item">
    <span class="nav-link">
<span class="menu-text">01-intro-wikipedia-data.ipynb</span>
    </span>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./02-pywikibot.html" aria-current="page"> 
<span class="menu-text">Accessing data from Wiki projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-wikidata.html"> 
<span class="menu-text">Using Wikidata</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">À propos</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sur cette page</h2>
   
  <ul>
<li>
<a href="#apis" id="toc-apis" class="nav-link active" data-scroll-target="#apis">APIs</a>
  <ul class="collapse">
<li><a href="#wikimedia-rest-api" id="toc-wikimedia-rest-api" class="nav-link" data-scroll-target="#wikimedia-rest-api">Wikimedia REST API</a></li>
  <li><a href="#mediawiki-rest-api" id="toc-mediawiki-rest-api" class="nav-link" data-scroll-target="#mediawiki-rest-api">MediaWiki REST API</a></li>
  <li><a href="#mediawiki-action-api" id="toc-mediawiki-action-api" class="nav-link" data-scroll-target="#mediawiki-action-api">MediaWiki Action API</a></li>
  </ul>
</li>
  <li>
<a href="#using-the-action-api-with-pywikibot" id="toc-using-the-action-api-with-pywikibot" class="nav-link" data-scroll-target="#using-the-action-api-with-pywikibot">Using the Action API with <em>PyWikiBot</em></a>
  <ul class="collapse">
<li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  </ul>
</li>
  <li>
<a href="#exploring-a-page-object" id="toc-exploring-a-page-object" class="nav-link" data-scroll-target="#exploring-a-page-object">Exploring a page object</a>
  <ul class="collapse">
<li><a href="#authorship" id="toc-authorship" class="nav-link" data-scroll-target="#authorship">Authorship</a></li>
  <li><a href="#contributors" id="toc-contributors" class="nav-link" data-scroll-target="#contributors">Contributors</a></li>
  <li><a href="#page-revisions" id="toc-page-revisions" class="nav-link" data-scroll-target="#page-revisions">Page revisions</a></li>
  <li><a href="#categories" id="toc-categories" class="nav-link" data-scroll-target="#categories">Categories</a></li>
  </ul>
</li>
  <li><a href="#exploring-a-user-object" id="toc-exploring-a-user-object" class="nav-link" data-scroll-target="#exploring-a-user-object">Exploring a user object</a></li>
  <li><a href="#accessing-categories" id="toc-accessing-categories" class="nav-link" data-scroll-target="#accessing-categories">Accessing categories</a></li>
  <li>
<a href="#aggregating-and-exploring-the-data" id="toc-aggregating-and-exploring-the-data" class="nav-link" data-scroll-target="#aggregating-and-exploring-the-data">Aggregating and Exploring the data</a>
  <ul class="collapse">
<li><a href="#using-a-single-page-as-an-example" id="toc-using-a-single-page-as-an-example" class="nav-link" data-scroll-target="#using-a-single-page-as-an-example">Using a single page as an example</a></li>
  <li><a href="#creating-a-dataframe-for-all-pages" id="toc-creating-a-dataframe-for-all-pages" class="nav-link" data-scroll-target="#creating-a-dataframe-for-all-pages">Creating a <code>DataFrame</code> for all pages</a></li>
  <li><a href="#creating-a-dataframe-for-editor-details" id="toc-creating-a-dataframe-for-editor-details" class="nav-link" data-scroll-target="#creating-a-dataframe-for-editor-details">Creating a dataframe for editor details</a></li>
  </ul>
</li>
  <li><a href="#conclusions-summary" id="toc-conclusions-summary" class="nav-link" data-scroll-target="#conclusions-summary">Conclusions &amp; Summary</a></li>
  </ul></nav>
</div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Accessing data from Wiki projects</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Wikipedia, and virtually all other Wiki projects that are run under the umbrella of the <a href="https://wikimediafoundation.org/">Wikimedia Foundation</a>, are using an open-source software called <em><a href="https://www.mediawiki.org/">MediaWiki</a></em>. It is also used outside the Wikimedia universe, in a wide range of settings. For example, researchers are aggregating information about biochemical pathways in the <a href="https://www.wikipathways.org/">WikiPathways</a> project, German-speaking patients with cluster headaches use it for <a href="https://ck-wissen.de/ckwiki/index.php?title=Hauptseite">creating their own knowledge base</a>, and in the <a href="https://wiki.openhumans.org/wiki/Personal_Science_Wiki"><em>Personal Science Wiki</em></a> people are sharing their n-of-1 citizen science efforts.</p>
<section id="apis" class="level2"><h2 class="anchored" data-anchor-id="apis">APIs</h2>
<p>To facilitate the programmatic and automatic access to the pages that people create, MediaWiki (and the Wikimedia Foundation) offer different APIs that can be used to access data and edit objects in Wikipedia and its many sister projects.</p>
<p>Namely, there are three different API classes with different focuses on use cases, two of which based are on the <a href="https://en.wikipedia.org/wiki/REST">REST</a> style:</p>
<ol type="1">
<li><strong><a href="https://www.mediawiki.org/wiki/Wikimedia_REST_API">Wikimedia REST API</a></strong></li>
<li><strong><a href="https://www.mediawiki.org/wiki/API:REST_API">MediaWiki REST API</a></strong></li>
<li><strong><a href="https://www.mediawiki.org/wiki/API:Action_API">MediaWiki Action API</a></strong></li>
</ol>
<section id="wikimedia-rest-api" class="level3"><h3 class="anchored" data-anchor-id="wikimedia-rest-api">Wikimedia REST API</h3>
<p>This custom API that is particular to the Wikimedia projects is designed for delivering high-throughput access to the content and metadata of Wikimedia projects in different, machine-readable formats. As a result, it offers a very narrow and highly optimized access to ‘live’ pages and content.</p>
<p>This focus makes it less relevant for research, where we might want to understand longitudinal changes in how articles have evolved.</p>
</section><section id="mediawiki-rest-api" class="level3"><h3 class="anchored" data-anchor-id="mediawiki-rest-api">MediaWiki REST API</h3>
<p>The standard REST API of MediaWiki is present in all MediaWiki installations and can be used to get data in JSON or HTML from them. Similar to the <em>Wikimedia</em>-specific API, this is mostly useful for accessing current data through simple API endpoints that return fast responses.</p>
<p>For those reasons, depending on the research question, it might be of limited utility.</p>
</section><section id="mediawiki-action-api" class="level3"><h3 class="anchored" data-anchor-id="mediawiki-action-api">MediaWiki Action API</h3>
<p>The Action API is the most powerful API that MediaWiki offers. Beyond accessing a wide range of data, it can even be used to submit and edit data. For this reason, it is also at the heart of the large <em>service bot</em> ecosystem of Wikipedia and its related projects. Run by Wikipedia contributors, these bots help detect wrongly formatted citations, replace broken links with still accessible archived versions, or fix common language issues.</p>
<p>It also offers the most possibilities to access data from Wikipedia for research purposes, as it provides the detailed edit histories of pages, allows detailed searches across pages and users, and also provides access to public user details, like a user’s editing history, gender (if provided) and other details.</p>
<p>We will focus on the Action API in the following materials.</p>
</section></section><section id="using-the-action-api-with-pywikibot" class="level2"><h2 class="anchored" data-anchor-id="using-the-action-api-with-pywikibot">Using the Action API with <em>PyWikiBot</em>
</h2>
<p>The <em>Action API</em> can be used through any programming language by sending correctly formatted HTTP requests to it, but as the API is very feature-rich, this quickly becomes quite complex.</p>
<p>Luckily, the Wikimedia Foundation maintains a Python library called <em><a href="https://doc.wikimedia.org/pywikibot/stable/index.html">Pywikibot</a></em> that can be used interact with the various endpoints the API offers and also wraps the responses into objects that are easier to work with. Importantly, it <strong>also ensures that we honor the rate limits</strong> of the API, to ensure we don’t overwhelm the server endpoints.</p>
<section id="setup" class="level3"><h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>The library can be installed through <code>pip</code> from the commandline:</p>
<pre><code>pip install pywikibot</code></pre>
<p>After the installation, we also need to create a user config, in which we need to add our username that we use to identify us as the user of the API. To create the file you can run the following from your terminal:</p>
<pre><code>pwb generate_user_files</code></pre>
<p>It creates a small <code>user-config.py</code> file in which we add the configuration details. This file should be <strong>located in the same folder from which you will run your Python scripts</strong>.</p>
<p>You can now start a Jupyter notebook and start interacting with the API.</p>
<p>First, to confirm that the config is found in the notebook, we run the following.</p>
<div id="8a6498ae-e76b-4e6c-bb53-119a6d587ba0" class="cell" data-execution_count="84">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>cat user<span class="op">-</span>config.py</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>family = 'wikipedia'
mylang = 'en'
usernames['wikipedia']['en'] = 'Gedankenstuecke'
password_file = None</code></pre>
</div>
</div>
<p>We see the username details, here for the English language-version of Wikipedia.</p>
<p>Now we can actually go ahead with loading the libary, confirming once more that the username was correctly set, and do our first query of Wikipedia through the library.</p>
<p>For that, we create a <code>site</code> object, that tells <code>pywikibot</code> which Wikimedia project we want to interact with, by giving the same 2-letter acronym of the language, and the project itself.</p>
<p>We can then use the site object to query through the <em>pywikibot</em>, for example for the page on computational social sciences:</p>
<div id="c2181fb0-2726-4a24-9ddd-2257a6e6824b" class="cell" data-execution_count="110">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pywikibot</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Config: </span><span class="sc">{}</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    pywikibot.config.usernames)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>site <span class="op">=</span> pywikibot.Site(<span class="st">'en'</span>, <span class="st">'wikipedia'</span>) <span class="co"># select the wikimedia project we want to interact with</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>page <span class="op">=</span> pywikibot.Page(site, <span class="st">"Computational social science"</span>) <span class="co"># give name of page we want to use</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Title: </span><span class="sc">{}</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    page.title()</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Start of article:</span><span class="ch">\n\n</span><span class="sc">{}</span><span class="st">…</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    page.text[:<span class="dv">1000</span>]</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    ))</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Config: defaultdict(&lt;class 'dict'&gt;, {'wikipedia': {'en': 'Gedankenstuecke'}, 'commons': {}})

Title: Computational social science

Start of article:

{{Short description|Academic sub-disciplines}}
{{broader|Quantitative social research}}

'''Computational social science''' is an interdisciplinary academic sub-field concerned with computational approaches to the [[social science]]s.
This means that computers are used to model, simulate, and analyze social phenomena. 
It has been applied in areas such as [[computational economics]], [[computational sociology]], computational media analysis, [[cliodynamics]], [[culturomics]], [[nonprofit studies]].&lt;ref&gt;{{Cite journal |last1=Ma |first1=Ji |last2=Ebeid |first2=Islam Akef |last3=de Wit |first3=Arjen |last4=Xu |first4=Meiying |last5=Yang |first5=Yongzheng |last6=Bekkers |first6=René |last7=Wiepking |first7=Pamala |date=February 2023 |title=Computational Social Science for Nonprofit Studies: Developing a Toolbox and Knowledge Base for the Field |journal=Voluntas |language=en |volume=34 |issue=1 |pages=52–63 |doi=10.1007/s11266-021-00414-x |issn=0957-8765|doi-access=free |hdl=1805/31787 |hdl…
</code></pre>
</div>
</div>
</section></section><section id="exploring-a-page-object" class="level2"><h2 class="anchored" data-anchor-id="exploring-a-page-object">Exploring a page object</h2>
<p>We now got the page on <em>Computational social science</em> in the <code>page</code> object and can access information from it, e.g. using a function like <code>page.title()</code> or accessing data like <code>page.text</code> above.</p>
<p>To see the full list of methods and values associated with it, we can see all of them like this (<code>dir(page)</code> in itself would show all methods, including private ones that aren’t supposed to be used directly).</p>
<div id="9212ef65-5baf-4510-b94d-0eab273a63d8" class="cell" data-execution_count="112">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>[i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">dir</span>(page) <span class="cf">if</span> <span class="kw">not</span> i.startswith(<span class="st">"_"</span>)]</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display" data-execution_count="112">
<pre><code>['WIKIBLAME_CODES',
 'WIKIWHO_CODES',
 'applicable_protections',
 'authorship',
 'autoFormat',
 'backlinks',
 'botMayEdit',
 'categories',
 'change_category',
 'clear_cache',
 'content_model',
 'contributors',
 'coordinates',
 'create_short_link',
 'data_item',
 'data_repository',
 'defaultsort',
 'delete',
 'depth',
 'embeddedin',
 'exists',
 'expand_text',
 'extlinks',
 'extract',
 'full_url',
 'get',
 'getCategoryRedirectTarget',
 'getDeletedRevision',
 'getOldVersion',
 'getRedirectTarget',
 'getReferences',
 'getVersionHistoryTable',
 'get_annotations',
 'get_best_claim',
 'get_parsed_page',
 'get_revision',
 'has_content',
 'has_deleted_revisions',
 'has_permission',
 'image_repository',
 'imagelinks',
 'interwiki',
 'isAutoTitle',
 'isCategoryRedirect',
 'isDisambig',
 'isIpEdit',
 'isRedirectPage',
 'isStaticRedirect',
 'isTalkPage',
 'is_categorypage',
 'is_filepage',
 'is_flow_page',
 'iterlanglinks',
 'itertemplates',
 'langlinks',
 'lastNonBotUser',
 'latest_revision',
 'latest_revision_id',
 'linkedPages',
 'loadDeletedRevisions',
 'main_authors',
 'markDeletedRevision',
 'merge_history',
 'move',
 'moved_target',
 'namespace',
 'oldest_revision',
 'page_image',
 'pageid',
 'permalink',
 'preloadText',
 'properties',
 'protect',
 'protection',
 'purge',
 'put',
 'raw_extracted_templates',
 'redirects',
 'revision_count',
 'revisions',
 'rollback',
 'save',
 'section',
 'set_redirect_target',
 'site',
 'templates',
 'templatesWithParams',
 'text',
 'title',
 'toggleTalkPage',
 'touch',
 'undelete',
 'userName',
 'version',
 'watch']</code></pre>
</div>
</div>
<p>There is a couple of interesting methods we will look at more closely: <code>authorship</code>, <code>contributors</code>, <code>revisions</code>, and <code>categories</code>.</p>
<section id="authorship" class="level3"><h3 class="anchored" data-anchor-id="authorship">Authorship</h3>
<p>To check how authorship for the current, i.e. latest version of the page distributes across different contributors, we can use the <code>authorship</code> method. Each tupel of the form <code>(1234, 50.0)</code> gives the authorship in character count (<code>1234</code>) and percentage of the article <code>(50.0</code>):</p>
<div id="a5fa9b5c-a737-4775-a476-baf99bdd0208" class="cell" data-execution_count="114">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>page.authorship()</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display" data-execution_count="114">
<pre><code>{'MattiNelimarkka': (3616, 23.0),
 'Hoyerdan': (3144, 20.0),
 '~2025-34400-27': (1257, 8.0),
 '46.233.116.47': (1100, 7.0),
 '2605:E000:1521:DB:B1CE:3E73:4742:6DD8': (786, 5.0)}</code></pre>
</div>
</div>
<p>We can see that both registered accounts (<code>MattiMelimarkka</code>) as well as anonymous contributors have made edits. In the past, anonymous contributions were saved under the IP address from which edits were made (e.g. <code>2605:E000:1521:DB:B1CE:3E73:4742:6DD8</code> or <code>46.233.116.47</code>), while today temporary user names are assigned (e.g. <code>~2025-34400-27</code>).</p>
</section><section id="contributors" class="level3"><h3 class="anchored" data-anchor-id="contributors">Contributors</h3>
<p>Instead of just looking at the latest version, we can also get the list of all people who ever contributed and their number of edits, using the <code>contributors</code> method, which will give us a tuple containing the username and the number of edits:</p>
<div id="4b2248d6-7d37-445a-869c-8f79dabb41fc" class="cell" data-execution_count="138">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="bu">list</span>(page.contributors())</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display" data-execution_count="138">
<pre><code>['SchlurcherBot',
 'Monkbot',
 'OAbot',
 '~2025-34400-27',
 'Folkezoft',
 'David Delony',
 'Allforrous',
 'Sythoz',
 'LucasBrown',
 'Citation bot',
 'Me, Myself, and I are Here',
 'Dicklyon',
 'MattiNelimarkka',
 'JCW-CleanerBot',
 '106.185.147.172',
 'WikiCleanerBot',
 'ContinueWithCaution',
 'Konila21',
 'Ira Leviton',
 '72.182.36.82',
 'Leosonh',
 'Jarble',
 'Liz',
 'MrOllie',
 'Xxpaulm',
 'Fgnievinski',
 'WheezePuppet',
 'InternetArchiveBot',
 '129.170.195.199',
 'Izno',
 '103.106.200.56',
 '2A01:C50E:2121:0:449F:4A20:B919:4EC2',
 'BHGbot',
 'Kvng',
 'Marnie Hawes',
 '45.243.222.143',
 'Fadesga',
 'IznoRepeat',
 'Christianssand',
 '217.16.13.130',
 'Smasongarrison',
 'GünniX',
 'Jeffwinchell',
 '193.227.11.122',
 'Deeahbz',
 'KolbertBot',
 'Askedonty',
 '197.48.29.120',
 'Fixuture',
 'Rjwilmsi',
 'Melcous',
 'Bigdata',
 '67.212.234.180',
 'HelpUsStopSpam',
 'Vonbergh',
 'Gilliam',
 '193.227.11.124',
 'Jauerback',
 'Alannanoellelaz',
 'BG19bot',
 '94.174.197.67',
 '46.233.116.47',
 'Oxf0',
 'Pleasantville',
 'Pturchin',
 'Hoyerdan',
 'Mwatson10',
 '2605:E000:1521:DB:B1CE:3E73:4742:6DD8',
 'SoSivr',
 '136.181.195.29',
 'De728631',
 'Alvin Seville',
 '2.85.160.139',
 'Bearcat',
 'Mamalbahador35',
 'CyberXRef',
 'Mr RD',
 'Malcolma',
 'DaveDixon']</code></pre>
</div>
</div>
<p>With this, we now also see some of the service bots that identify as such in their name already, like the <code>WikiCleanerBot</code> or the <code>InternetArchiveBot</code>.</p>
</section><section id="page-revisions" class="level3"><h3 class="anchored" data-anchor-id="page-revisions">Page revisions</h3>
<p>If we want to understand the actual editing history of the page, we can get a list of all revisions, which allows us to see how the page evolved over time.</p>
<p>Note: We’ll just look at the 10 most recent edits to keep the notebook a bit cleaner, but in principle you can see all edits:</p>
<div id="e41197ac-42fb-422a-8b4e-9d9536b1b115" class="cell" data-execution_count="124">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"This page has </span><span class="sc">{}</span><span class="st"> revisions"</span>.<span class="bu">format</span>(page.revision_count()))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>rev <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> revision <span class="kw">in</span> page.revisions():</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"</span><span class="sc">{}</span><span class="st"> edited the article on </span><span class="sc">{}</span><span class="st"> with this edit comment:</span><span class="ch">\n\t</span><span class="sc">{}</span><span class="ch">\n</span><span class="st">---"</span>.<span class="bu">format</span>(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>        revision[<span class="st">'user'</span>],</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>        revision[<span class="st">'timestamp'</span>],</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>        revision[<span class="st">'comment'</span>]))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    rev <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> rev <span class="op">&gt;</span> <span class="dv">10</span>:</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">break</span></span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>This page has 135 revisions
SchlurcherBot edited the article on 2026-02-12T21:46:58Z with this edit comment:
    Bot: http → https
---
Monkbot edited the article on 2025-11-27T20:44:07Z with this edit comment:
    /* Definitions */ [[User:Monkbot/task 21: Replace page(s) with article-number|Monkbot/task 21: Replace page(s) with article-number]];
---
OAbot edited the article on 2025-11-24T07:09:33Z with this edit comment:
    [[Wikipedia:OABOT|Open access bot]]: pmc updated in citation with #oabot.
---
~2025-34400-27 edited the article on 2025-11-18T00:06:45Z with this edit comment:
    Added Gilardi and Bermejo as benchmarks against humans
---
Monkbot edited the article on 2025-09-30T07:15:29Z with this edit comment:
    /* Definitions */ [[User:Monkbot/task 21: Replace page(s) with article-number|Monkbot/task 21: Replace page(s) with article-number]];
---
Folkezoft edited the article on 2025-08-13T03:00:35Z with this edit comment:
    /* Definitions */ Tag [[Wikipedia:Bare URLs|Bare URLs]] using [[Wikipedia:AutoWikiBrowser|AWB]]
---
David Delony edited the article on 2025-04-21T00:43:12Z with this edit comment:
    /* See also */ Added link to computational statistics article.
---
Allforrous edited the article on 2025-02-27T22:44:19Z with this edit comment:
    /* External links */ Commonscat template.
---
Sythoz edited the article on 2024-12-11T18:29:28Z with this edit comment:
    removed too special database history link, added "social physics" to the "See also"
---
LucasBrown edited the article on 2024-05-08T15:01:44Z with this edit comment:
    Adding local [[Wikipedia:Short description|short description]]: "Academic sub-disciplines", overriding Wikidata description "academic sub-disciplines concerned with computational approaches to the social sciences"
---
Citation bot edited the article on 2024-04-04T11:56:42Z with this edit comment:
    Altered journal. Add: bibcode, title, authors 1-1. Removed URL that duplicated identifier. Changed bare reference to CS1/2. Removed parameters. Some additions/deletions were parameter name changes. | [[:en:WP:UCB|Use this bot]]. [[:en:WP:DBUG|Report bugs]]. | Suggested by Abductive | [[Category:Wikipedia articles in need of updating from March 2024]] | #UCB_Category 101/720
---</code></pre>
</div>
</div>
<p>By default, the revisions that are returned do not include the text of the previous revisions, but if we pass <code>content=True</code> in the method call, those will be returned too:</p>
<div id="6b4e68e8-7bee-40b4-bb13-190470f033e6" class="cell" data-execution_count="130">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> revision <span class="kw">in</span> page.revisions(content<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(revision.text[:<span class="dv">500</span>])</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">break</span></span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>{{Short description|Academic sub-disciplines}}
{{broader|Quantitative social research}}

'''Computational social science''' is an interdisciplinary academic sub-field concerned with computational approaches to the [[social science]]s.
This means that computers are used to model, simulate, and analyze social phenomena. 
It has been applied in areas such as [[computational economics]], [[computational sociology]], computational media analysis, [[cliodynamics]], [[culturomics]], [[nonprofit studies</code></pre>
</div>
</div>
</section><section id="categories" class="level3"><h3 class="anchored" data-anchor-id="categories">Categories</h3>
<p>In Wikipedia, virtually all articles are in one to many different categories. We can explore which category a page belongs to through the <code>page.categories</code> method:</p>
<div id="9a2be144-78cc-4fc3-8692-99c05c4b165c" class="cell" data-execution_count="133">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cat <span class="kw">in</span> page.categories():</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(cat)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[en:Category:All Wikipedia articles in need of updating]]
[[en:Category:All articles with bare URLs for citations]]
[[en:Category:Articles with bare URLs for citations from August 2025]]
[[en:Category:Articles with short description]]
[[en:Category:Commons category link is defined as the pagename]]
[[en:Category:Computational social science]]
[[en:Category:Short description is different from Wikidata]]
[[en:Category:Webarchive template wayback links]]
[[en:Category:Wikipedia articles in need of updating from March 2024]]</code></pre>
</div>
</div>
</section></section><section id="exploring-a-user-object" class="level2"><h2 class="anchored" data-anchor-id="exploring-a-user-object">Exploring a user object</h2>
<p>Above, we have seen how we can access pages in Wikipedia and also get some details about how edited that given page. The API also offers method to dig a bit into who those contributors are and what edits they made.</p>
<p>To access details about a single user, we can use <code>pywikibot.User</code> and then look at the methods that are accessible:</p>
<div id="bb6dcf5b-f049-4f53-ad07-c8c621551b20" class="cell" data-execution_count="153">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>user <span class="op">=</span> pywikibot.User(site, <span class="st">"Gedankenstuecke"</span>) </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>[i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">dir</span>(user) <span class="cf">if</span> <span class="kw">not</span> i.startswith(<span class="st">"_"</span>)]</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display" data-execution_count="153">
<pre><code>['WIKIBLAME_CODES',
 'WIKIWHO_CODES',
 'applicable_protections',
 'authorship',
 'autoFormat',
 'backlinks',
 'block',
 'botMayEdit',
 'categories',
 'change_category',
 'clear_cache',
 'content_model',
 'contributions',
 'contributors',
 'coordinates',
 'create_short_link',
 'data_item',
 'data_repository',
 'defaultsort',
 'delete',
 'deleted_contributions',
 'depth',
 'editCount',
 'embeddedin',
 'exists',
 'expand_text',
 'extlinks',
 'extract',
 'first_edit',
 'full_url',
 'gender',
 'get',
 'getCategoryRedirectTarget',
 'getDeletedRevision',
 'getOldVersion',
 'getRedirectTarget',
 'getReferences',
 'getUserPage',
 'getUserTalkPage',
 'getVersionHistoryTable',
 'get_annotations',
 'get_best_claim',
 'get_block_info',
 'get_parsed_page',
 'get_revision',
 'getprops',
 'groups',
 'has_content',
 'has_deleted_revisions',
 'has_permission',
 'image_repository',
 'imagelinks',
 'interwiki',
 'isAnonymous',
 'isAutoTitle',
 'isCategoryRedirect',
 'isDisambig',
 'isEmailable',
 'isIpEdit',
 'isRedirectPage',
 'isRegistered',
 'isStaticRedirect',
 'isTalkPage',
 'is_CIDR',
 'is_blocked',
 'is_categorypage',
 'is_filepage',
 'is_flow_page',
 'is_locked',
 'is_partial_blocked',
 'is_thankable',
 'iterlanglinks',
 'itertemplates',
 'langlinks',
 'lastNonBotUser',
 'last_activity',
 'last_edit',
 'last_event',
 'latest_revision',
 'latest_revision_id',
 'linkedPages',
 'loadDeletedRevisions',
 'logevents',
 'main_authors',
 'markDeletedRevision',
 'merge_history',
 'move',
 'moved_target',
 'namespace',
 'oldest_revision',
 'page_image',
 'pageid',
 'permalink',
 'preloadText',
 'properties',
 'protect',
 'protection',
 'purge',
 'put',
 'raw_extracted_templates',
 'redirects',
 'registration',
 'renamed_target',
 'revision_count',
 'revisions',
 'rights',
 'rollback',
 'save',
 'section',
 'send_email',
 'set_redirect_target',
 'site',
 'templates',
 'templatesWithParams',
 'text',
 'title',
 'toggleTalkPage',
 'touch',
 'unblock',
 'undelete',
 'uploadedImages',
 'userName',
 'username',
 'version',
 'watch']</code></pre>
</div>
</div>
<p>Some interesting bits for users are the <code>editCount</code>, if they gave their gender, if they are currently blocked from editing, and also what contributions they made. Let’s explore those:</p>
<div id="2d2ae99d-aa90-417a-b87b-361752d222b2" class="cell" data-execution_count="164">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"user gave gender as </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    user.gender()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"user is blocked? </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    user.is_blocked()</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"user made </span><span class="sc">{}</span><span class="st"> edits</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    user.editCount()</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"user contributions:"</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>c <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> contrib <span class="kw">in</span> user.contributions():</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(contrib)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    c <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> c <span class="op">&gt;</span> <span class="dv">10</span>:</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">break</span></span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>user gave gender as unknown
user is blocked? False
user made 149 edits

user contributions:
(Page('Sierras de Córdoba'), 1352554752, Timestamp(2026, 5, 4, 22, 8, 44), 'fix name of cerro mogote')
(Page('Sierras de Córdoba'), 1352554625, Timestamp(2026, 5, 4, 22, 7, 29), 'add details about los gigantes as natural reserve and tourism spot')
(Page('Los Gigantes'), 1352553589, Timestamp(2026, 5, 4, 21, 57, 18), 'add disambiguation option')
(Page('Draft:Stuart Vines'), 1351709685, Timestamp(2026, 4, 29, 17, 26, 26), 'fix name spelling in infobox')
(Page('Draft:Stuart Vines'), 1351703667, Timestamp(2026, 4, 29, 16, 36, 38), 'Submitting using [[WP:AFCSW|AfC-submit-wizard]]')
(Page('Draft talk:Stuart Vines'), 1351703585, Timestamp(2026, 4, 29, 16, 35, 39), 'Adding WikiProject tags ([[MediaWiki:AFC-add-project-tags.js|assisted]])')
(Page('Draft:Stuart Vines'), 1351703472, Timestamp(2026, 4, 29, 16, 34, 49), '-- Draft creation using the [[WP:Article wizard]] --')
(Page('Tupungato'), 1351597508, Timestamp(2026, 4, 29, 0, 10, 30), 'add detail to first ascent')
(Page('Tupungato'), 1351586099, Timestamp(2026, 4, 28, 22, 31, 2), "add eastern ascent by Viero and Rabal, their death and recovery of Viero's backpack incl. proof of ascent")
(Page('Talk:Darren Beattie'), 1350906013, Timestamp(2026, 4, 24, 19, 15, 45), '/* Involvement in policy for visa restrictions against noncitizen researchers, fact-checkers, and trust/safety workers */ new section')
(Page('UK Biobank'), 1350766688, Timestamp(2026, 4, 23, 22, 15), 'add coverage about uk biobank data for sale on alibaba')</code></pre>
</div>
</div>
</section><section id="accessing-categories" class="level2"><h2 class="anchored" data-anchor-id="accessing-categories">Accessing categories</h2>
<p>We have already seen that pages can be in different categories that group pages that belong together. We can also use categories as a starting point to get a collection of related pages. To do that, we use the <code>pywikibot.Category</code> method, using the <em>Kenyan politicians</em> category as a starting point:</p>
<div id="44cb5840-c600-4d20-bc0f-c627d759d28a" class="cell" data-execution_count="166">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>site <span class="op">=</span> pywikibot.Site(<span class="st">'en'</span>, <span class="st">'wikipedia'</span>) <span class="co"># select the wikimedia project we want to interact with</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>politician_pages <span class="op">=</span> [] <span class="co"># to store page names and handles after iterating over category</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>category <span class="op">=</span> pywikibot.Category(site, <span class="st">"Kenyan politicians"</span>) <span class="co"># select category</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> category.articles():</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    politician_pages.append(i)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"There are </span><span class="sc">{}</span><span class="st"> pages in the 'Kenyan politicians' category"</span>.<span class="bu">format</span>(<span class="bu">len</span>(politician_pages)))</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 102 pages in the 'Kenyan politicians' category</code></pre>
</div>
</div>
<p>By iterating over the category, we find 102 pages that are part of it. A good starting point, but in reality, the English language edition of Wikipedia has more pages about Kenyan politicians and who aren’t listed in this category, due to how sub-categories in Wikipedia work.</p>
<p>If we go to the Category on Wikipedia, we see 12 sub-categories for e.g. <em>Kenyan politicians by party</em>, <em>stubs</em> (new/short articles) and more.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/e7e46c24-b78b-47e1-9789-734e0bc8bddb-1-3e410b66-4ef3-4309-ac82-02ceba1fbadd.png" class="img-fluid figure-img"></p>
<figcaption>image.png</figcaption></figure>
</div>
<p>Pages in these sub-categories won’t be listed as part of the higher-level category by default. But we can recurse through those lists to ensure that we also get those pages in the subcategories:</p>
<div id="98acae50-f05d-4112-bf9d-a5b66fce3fd0" class="cell" data-execution_count="167">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> category.articles(recurse<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    politician_pages.append(i)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"There are </span><span class="sc">{}</span><span class="st"> pages in the 'Kenyan politicians' category"</span>.<span class="bu">format</span>(<span class="bu">len</span>(politician_pages)))</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 1039 pages in the 'Kenyan politicians' category</code></pre>
</div>
</div>
<p>This now gives us a substantially larger number of pages about Kenyan politicians to work with.</p>
</section><section id="aggregating-and-exploring-the-data" class="level2"><h2 class="anchored" data-anchor-id="aggregating-and-exploring-the-data">Aggregating and Exploring the data</h2>
<p>Now that we have seen the different ways that we can access this data, let’s start to aggregate and visually explore this data a bit.</p>
<p>Ultimately, we would like to have a large <code>DataFrame</code> or table, that contains the full edit history for all the pages in our category of interest.</p>
<section id="using-a-single-page-as-an-example" class="level3"><h3 class="anchored" data-anchor-id="using-a-single-page-as-an-example">Using a single page as an example</h3>
<p>But, for a start, let’s demonstrate the process by using a single page of the category for demonstration purposes - and then plot the contributions per user to this article – as measured by the number of submitted revisions and the total of added/removed characters as well.</p>
<p>We then:</p>
<ol type="1">
<li>get all the revisions into a dataframe</li>
<li>add the page title (which we will need for merging all pages into one table later on), and</li>
<li>calculate the size difference of the article, to evaluate how much text each edit added/removed</li>
</ol>
<div id="f6872be7-cdd5-45f2-8c68-1b61dbb7454a" class="cell" data-execution_count="172">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd <span class="co"># load pandas to get Dataframes and all related methods</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> politician_pages[<span class="dv">2</span>] <span class="co"># pick an article</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># get all revisions for the article, including the actual article</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(p.revisions(content<span class="op">=</span><span class="va">True</span>)) </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># add title, which is missing from revisions, as new column `page_title`</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'page_title'</span>] <span class="op">=</span> p.title() </span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate size difference between revisions using current/previous revision</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'size_difference'</span>] <span class="op">=</span> df[<span class="st">'size'</span>] <span class="op">-</span> df[<span class="st">'size'</span>].shift(periods<span class="op">=-</span><span class="dv">1</span>, fill_value<span class="op">=</span><span class="dv">0</span>) </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">5</span>)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display" data-execution_count="172">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead><tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">revid</th>
<th data-quarto-table-cell-role="th">parentid</th>
<th data-quarto-table-cell-role="th">user</th>
<th data-quarto-table-cell-role="th">temp</th>
<th data-quarto-table-cell-role="th">userid</th>
<th data-quarto-table-cell-role="th">timestamp</th>
<th data-quarto-table-cell-role="th">size</th>
<th data-quarto-table-cell-role="th">sha1</th>
<th data-quarto-table-cell-role="th">roles</th>
<th data-quarto-table-cell-role="th">slots</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">parsedcomment</th>
<th data-quarto-table-cell-role="th">tags</th>
<th data-quarto-table-cell-role="th">anon</th>
<th data-quarto-table-cell-role="th">minor</th>
<th data-quarto-table-cell-role="th">userhidden</th>
<th data-quarto-table-cell-role="th">commenthidden</th>
<th data-quarto-table-cell-role="th">text</th>
<th data-quarto-table-cell-role="th">contentmodel</th>
<th data-quarto-table-cell-role="th">page_title</th>
<th data-quarto-table-cell-role="th">size_difference</th>
</tr></thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1353017535</td>
<td>1352955026</td>
<td>~2026-27873-85</td>
<td></td>
<td>53666482</td>
<td>2026-05-07 17:27:58</td>
<td>11702</td>
<td>54f895c341ba5e02ffaee873e5003946a7571ada</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>&lt;span class="autocomment"&gt;&lt;a href="/wiki/Rosly...</td>
<td>[mobile edit, mobile web edit]</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{Short description|Kenyan politician (born 19...</td>
<td>wikitext</td>
<td>Roslyne Akombe</td>
<td>-8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1352955026</td>
<td>1345291761</td>
<td>~2026-27566-80</td>
<td></td>
<td>53657954</td>
<td>2026-05-07 06:56:46</td>
<td>11710</td>
<td>e6578bd9c7ae21879052ce70ed519d8c047ced07</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td></td>
<td>[wikieditor]</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{Short description|Kenyan politician (born 19...</td>
<td>wikitext</td>
<td>Roslyne Akombe</td>
<td>16</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1345291761</td>
<td>1342238182</td>
<td>LionmerterTHE</td>
<td>NaN</td>
<td>49865477</td>
<td>2026-03-25 10:34:29</td>
<td>11694</td>
<td>98f8589ccba62702aa5d4b4611a4a8c3b0caea6a</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>&lt;span class="autocomment"&gt;&lt;a href="/wiki/Rosly...</td>
<td>[AWB]</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>{{Short description|Kenyan politician (born 19...</td>
<td>wikitext</td>
<td>Roslyne Akombe</td>
<td>-1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1342238182</td>
<td>1327823244</td>
<td>Ser Amantio di Nicolao</td>
<td>NaN</td>
<td>753665</td>
<td>2026-03-07 21:29:55</td>
<td>11695</td>
<td>8631fa0b036c31c21567e51cac3cb44a82b3ecb6</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>&lt;span class="autocomment"&gt;&lt;a href="/wiki/Rosly...</td>
<td>[AWB]</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{Short description|Kenyan politician (born 19...</td>
<td>wikitext</td>
<td>Roslyne Akombe</td>
<td>-25</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1327823244</td>
<td>1327823189</td>
<td>Eleosyne</td>
<td>NaN</td>
<td>49749298</td>
<td>2025-12-16 08:04:46</td>
<td>11720</td>
<td>b1c7e676b7268b23f046cd7e7b78f14109d50156</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>Added  a category</td>
<td>[visualeditor]</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{Short description|Kenyan politician (born 19...</td>
<td>wikitext</td>
<td>Roslyne Akombe</td>
<td>30</td>
</tr>
</tbody>
</table>
<p>5 rows × 21 columns</p>
</div>
</div>
</div>
<section id="plotting-the-number-of-edits-per-editor" class="level4"><h4 class="anchored" data-anchor-id="plotting-the-number-of-edits-per-editor">Plotting the number of edits per editor</h4>
<p>For this chosen page, let’s now visualize the number of edits made by the different editors as measured by saved revisions:</p>
<div id="87fb74b1-521d-4ccf-b3fc-decf335b2197" class="cell" data-execution_count="175">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df.groupby([<span class="st">"user"</span>]).count()[<span class="st">'userid'</span>].plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">10</span>))</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section><section id="plotting-the-overall-size-change-made-by-the-editor" class="level4"><h4 class="anchored" data-anchor-id="plotting-the-overall-size-change-made-by-the-editor">Plotting the overall size change made by the editor</h4>
<p>The number of revisions of course does not tell us everything. Some editors might make big edits in a single change, while others might break their edits in many small changes. And some might mostly add new information, while others delete outdated/wrong details. So let’s look at the ‘article szie changes’ per editor:</p>
<p>Note: A user could show up as “zero” edits, if they added and removed text of the same volume</p>
<div id="75e4597f-5d13-425a-90bb-13adf9ec3f08" class="cell" data-execution_count="178">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df.groupby(<span class="st">'user'</span>)[<span class="st">'size_difference'</span>].<span class="bu">sum</span>().plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">10</span>))</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="creating-a-dataframe-for-all-pages" class="level3"><h3 class="anchored" data-anchor-id="creating-a-dataframe-for-all-pages">Creating a <code>DataFrame</code> for all pages</h3>
<p>Now that we better understand the type of data we will get, and got a working code to create a <code>DataFrame</code> over all revisions of a single page, let’s zoom one more step out - and create it for all pages in our category.</p>
<p><strong>Warning:</strong> Actually executing this code will likely take a while given the API rate limits that MediaWiki enforces and that <em>Pywikibot</em> will respect.</p>
<div id="593a90b9-2e03-49a5-9dbe-00fb1804b3c8" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create empty dataframe to hold all data eventually</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df_politicians <span class="op">=</span> pd.DataFrame()</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> politician_pages:</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># create dataframe that holds the revisions for a given page</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># also add the title &amp; size diff as above</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.DataFrame(p.revisions(content<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'page_title'</span>] <span class="op">=</span> p.title() </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'size_difference'</span>] <span class="op">=</span> df[<span class="st">'size'</span>] <span class="op">-</span> df[<span class="st">'size'</span>].shift(periods<span class="op">=-</span><span class="dv">1</span>, fill_value<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># if this is not first iteration, concatenate existing data &amp; new page</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> df_politicians.empty:</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>        df_politicians <span class="op">=</span> pd.concat([df_politicians, df])</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># otherwise just create aggregate DF </span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>        df_politicians <span class="op">=</span> df</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's save our data in a CSV file, especially given how long it can take to run this</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>df_politicians.to_csv(<span class="st">'pages_category_kenyian_politicians.csv'</span>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>df_politicians.head()</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead><tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">revid</th>
<th data-quarto-table-cell-role="th">parentid</th>
<th data-quarto-table-cell-role="th">minor</th>
<th data-quarto-table-cell-role="th">user</th>
<th data-quarto-table-cell-role="th">userid</th>
<th data-quarto-table-cell-role="th">timestamp</th>
<th data-quarto-table-cell-role="th">size</th>
<th data-quarto-table-cell-role="th">sha1</th>
<th data-quarto-table-cell-role="th">roles</th>
<th data-quarto-table-cell-role="th">slots</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">anon</th>
<th data-quarto-table-cell-role="th">userhidden</th>
<th data-quarto-table-cell-role="th">commenthidden</th>
<th data-quarto-table-cell-role="th">text</th>
<th data-quarto-table-cell-role="th">contentmodel</th>
<th data-quarto-table-cell-role="th">page_title</th>
<th data-quarto-table-cell-role="th">size_difference</th>
<th data-quarto-table-cell-role="th">temp</th>
<th data-quarto-table-cell-role="th">sha1hidden</th>
<th data-quarto-table-cell-role="th">suppressed</th>
</tr></thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1285549690</td>
<td>1284245409</td>
<td>True</td>
<td>Almaddy2022</td>
<td>44620763.0</td>
<td>2025-04-14 10:08:57</td>
<td>4224</td>
<td>dac6097a46b4f8553538a7cd72f8e21144a98f25</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{short description|Kenyan writer and politica...</td>
<td>wikitext</td>
<td>Abdilatif Abdalla</td>
<td>8</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1284245409</td>
<td>1241910337</td>
<td>False</td>
<td>Almaddy2022</td>
<td>44620763.0</td>
<td>2025-04-06 12:24:59</td>
<td>4216</td>
<td>9702f3020b6af39bfe3d4c665ddff5caa65b9b51</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{short description|Kenyan writer and politica...</td>
<td>wikitext</td>
<td>Abdilatif Abdalla</td>
<td>93</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1241910337</td>
<td>1215802812</td>
<td>True</td>
<td>Inter&amp;anthro</td>
<td>18180119.0</td>
<td>2024-08-23 20:59:25</td>
<td>4123</td>
<td>3855f560b43074cb4ddf410042636935866d6e54</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{short description|Kenyan writer and politica...</td>
<td>wikitext</td>
<td>Abdilatif Abdalla</td>
<td>38</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1215802812</td>
<td>1215802775</td>
<td>False</td>
<td>IOHANNVSVERVS</td>
<td>24759391.0</td>
<td>2024-03-27 06:08:59</td>
<td>4085</td>
<td>edde49d1d4e95abcdd491f4e142fdd2f3fed23eb</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{short description|Kenyan writer and politica...</td>
<td>wikitext</td>
<td>Abdilatif Abdalla</td>
<td>-1</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1215802775</td>
<td>1215802684</td>
<td>False</td>
<td>IOHANNVSVERVS</td>
<td>24759391.0</td>
<td>2024-03-27 06:08:39</td>
<td>4086</td>
<td>6e4050681632db2525ccc51e26e2cf99ab2a9a42</td>
<td>[main]</td>
<td>{'main': {'contentmodel': 'wikitext', 'content...</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>{{short description|Kenyan writer and politica...</td>
<td>wikitext</td>
<td>Abdilatif Abdalla</td>
<td>13</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>
<p>5 rows × 23 columns</p>
</div>
</div>
</div>
<section id="making-one-large-plot-of-number-of-edits-per-page" class="level4"><h4 class="anchored" data-anchor-id="making-one-large-plot-of-number-of-edits-per-page">Making one large plot of number of edits per page</h4>
<p>Now we can group the number of revisions per page title and put it all in one plot</p>
<div id="44b25471-2432-4d22-a9e6-ff818e27a933" class="cell" data-execution_count="148">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>df_politicians.groupby([<span class="st">"page_title"</span>]).count()[<span class="st">'user'</span>].plot(kind<span class="op">=</span><span class="st">'bar'</span>,figsize<span class="op">=</span>(<span class="dv">30</span>,<span class="dv">10</span>))</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Seems like there’s one article with a huge number of edits compared to all others, plus some more that stand out. Let’s try to find those:</p>
<div id="df8132fe-f6c1-4a89-a97b-7b9611ced8a2" class="cell" data-execution_count="191">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df_politicians.groupby([<span class="st">'page_title'</span>]).count().sort_values(by<span class="op">=</span>[<span class="st">'revid'</span>], ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">9</span>)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display" data-execution_count="191">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">revid</th>
<th data-quarto-table-cell-role="th">parentid</th>
<th data-quarto-table-cell-role="th">minor</th>
<th data-quarto-table-cell-role="th">user</th>
<th data-quarto-table-cell-role="th">userid</th>
<th data-quarto-table-cell-role="th">timestamp</th>
<th data-quarto-table-cell-role="th">size</th>
<th data-quarto-table-cell-role="th">sha1</th>
<th data-quarto-table-cell-role="th">roles</th>
<th data-quarto-table-cell-role="th">slots</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">tags</th>
<th data-quarto-table-cell-role="th">anon</th>
<th data-quarto-table-cell-role="th">userhidden</th>
<th data-quarto-table-cell-role="th">commenthidden</th>
<th data-quarto-table-cell-role="th">text</th>
<th data-quarto-table-cell-role="th">contentmodel</th>
<th data-quarto-table-cell-role="th">size_difference</th>
<th data-quarto-table-cell-role="th">temp</th>
<th data-quarto-table-cell-role="th">sha1hidden</th>
<th data-quarto-table-cell-role="th">suppressed</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">page_title</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Elizabeth II</th>
<td>18393</td>
<td>18393</td>
<td>18393</td>
<td>18393</td>
<td>18393</td>
<td>18393</td>
<td>18393</td>
<td>18390</td>
<td>18393</td>
<td>18393</td>
<td>...</td>
<td>18393</td>
<td>18393</td>
<td>18393</td>
<td>18393</td>
<td>18390</td>
<td>18393</td>
<td>18393</td>
<td>0</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Jomo Kenyatta</th>
<td>3268</td>
<td>3268</td>
<td>3268</td>
<td>3268</td>
<td>3268</td>
<td>3268</td>
<td>3268</td>
<td>3266</td>
<td>3268</td>
<td>3268</td>
<td>...</td>
<td>3268</td>
<td>3268</td>
<td>3268</td>
<td>3268</td>
<td>3266</td>
<td>3268</td>
<td>3268</td>
<td>0</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Raila Odinga</th>
<td>3157</td>
<td>3157</td>
<td>3157</td>
<td>3157</td>
<td>3157</td>
<td>3157</td>
<td>3157</td>
<td>3141</td>
<td>3157</td>
<td>3157</td>
<td>...</td>
<td>3157</td>
<td>3157</td>
<td>3157</td>
<td>3157</td>
<td>3141</td>
<td>3157</td>
<td>3157</td>
<td>0</td>
<td>16</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Barack Obama Sr.</th>
<td>2876</td>
<td>2876</td>
<td>2876</td>
<td>2876</td>
<td>2867</td>
<td>2876</td>
<td>2876</td>
<td>2840</td>
<td>2876</td>
<td>2876</td>
<td>...</td>
<td>2876</td>
<td>2876</td>
<td>2876</td>
<td>2876</td>
<td>2840</td>
<td>2876</td>
<td>2876</td>
<td>0</td>
<td>36</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Uhuru Kenyatta</th>
<td>2554</td>
<td>2554</td>
<td>2554</td>
<td>2554</td>
<td>2554</td>
<td>2554</td>
<td>2554</td>
<td>2544</td>
<td>2554</td>
<td>2554</td>
<td>...</td>
<td>2554</td>
<td>2554</td>
<td>2554</td>
<td>2554</td>
<td>2544</td>
<td>2554</td>
<td>2554</td>
<td>19</td>
<td>10</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Mwai Kibaki</th>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>...</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>2436</td>
<td>5</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">William Ruto</th>
<td>2420</td>
<td>2420</td>
<td>2420</td>
<td>2420</td>
<td>2420</td>
<td>2420</td>
<td>2420</td>
<td>2414</td>
<td>2420</td>
<td>2420</td>
<td>...</td>
<td>2420</td>
<td>2420</td>
<td>2420</td>
<td>2420</td>
<td>2414</td>
<td>2420</td>
<td>2420</td>
<td>9</td>
<td>6</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Wangarĩ Maathai</th>
<td>2088</td>
<td>2088</td>
<td>2088</td>
<td>2088</td>
<td>2088</td>
<td>2088</td>
<td>2088</td>
<td>2080</td>
<td>2088</td>
<td>2088</td>
<td>...</td>
<td>2088</td>
<td>2088</td>
<td>2088</td>
<td>2088</td>
<td>2080</td>
<td>2088</td>
<td>2088</td>
<td>5</td>
<td>8</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Jomo Kenyatta International Airport</th>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>...</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>2072</td>
<td>4</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>9 rows × 22 columns</p>
</div>
</div>
</div>
<p>If we look closely, there seems to be something noteworthy with those search results: Why did the “Elizabeth II” <strong>and</strong> “Jomo Kenyatta International Airport” make our list of politicians?! Let’s hold that thought for a bit longer, when we’ll explore an alternative way to narrow down our pages of interest.</p>
</section></section><section id="creating-a-dataframe-for-editor-details" class="level3"><h3 class="anchored" data-anchor-id="creating-a-dataframe-for-editor-details">Creating a dataframe for editor details</h3>
<p>For now, let’s do a similar approach for saving the details of the editors that have touched those pages that we have identified.</p>
<p>For a start, let’s just save the basic statistics for them, namely their total edit counts, gender (if entered), and whether they are registered users and/or bots.</p>
<p>Bots in Wikimedia are marked by the user group they belong to, so we can use the <code>.groups()</code> method and check if the account is part of it.</p>
<p>Getting all those user details will take a long while, given that it’s &gt; 20.000, so for demonstration purposes, the code below only does it for the first 100 users.</p>
<div id="7d44193d-85ae-4c48-91a1-51ef8d6826e3" class="cell">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>df_users <span class="op">=</span> pd.DataFrame()</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>count <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> user <span class="kw">in</span> df_politicians[<span class="st">'user'</span>].unique():</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    user <span class="op">=</span> pywikibot.User(site, user) <span class="co"># get user object to manipulate</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    groups <span class="op">=</span> user.groups()</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">"bot"</span> <span class="kw">in</span> groups: <span class="co"># to make it easier to see if user is a bot</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>        bot <span class="op">=</span> <span class="va">True</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>        bot <span class="op">=</span> <span class="va">False</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(user.first_edit) <span class="op">&gt;</span> <span class="dv">2</span>: <span class="co"># doesn't necessarily exist for some reason</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>        first_edit <span class="op">=</span> user.first_edit[<span class="dv">2</span>]</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>        first_edit <span class="op">=</span> <span class="va">None</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(user.last_edit) <span class="op">&gt;</span> <span class="dv">2</span>: <span class="co"># doesn't necessarily exist for some reason</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>        last_edit <span class="op">=</span> user.last_edit[<span class="dv">2</span>]</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>        last_edit <span class="op">=</span> <span class="va">None</span>    </span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.DataFrame([{</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>        <span class="st">'username'</span> : user.username,</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>        <span class="st">'is_blocked'</span>: user.is_blocked(),</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>        <span class="st">'gender'</span>: user.gender(),</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">'is_bot'</span>: bot,</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">'first_edit'</span>: first_edit,</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">'last_edit'</span>: last_edit,</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">'editCount'</span>: user.editCount()</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>    }]</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> df_users.empty:</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>        df_users <span class="op">=</span> pd.concat([df_users, df])</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>        df_users <span class="op">=</span> df</span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>    count <span class="op">+=</span> <span class="dv">1</span> </span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> count <span class="op">&gt;</span> <span class="dv">100</span>:</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a>        <span class="co">#pass</span></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>        <span class="co"># otherwise, this runs for a very long time to actually get all the user data!</span></span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>        <span class="cf">break</span></span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>df_users.head(<span class="dv">100</span>)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<div id="1ef28652-0e50-457e-86a6-46633d26ab9d" class="cell" data-execution_count="192">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use this to save the full list of users if you've used it, by uncommenting the line below</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># df_users.to_csv('users_who_edited_kenyian_politicians.csv')</span></span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<section id="plotting-the-edit-per-user" class="level4"><h4 class="anchored" data-anchor-id="plotting-the-edit-per-user">Plotting the edit per user</h4>
<p>Now, we can look at the editing behaviour of all of those users, across all articles they edited, by starting to make some plots.</p>
<p>Let’s start with a basic histogram over the edit counts. The x-axis will show us the number of edits in bins, the y-axis how many users made that many edits:</p>
<div id="27a3dedb-828f-4f19-ad1d-bd9cadc133e5" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df_users[<span class="st">'editCount'</span>].plot(kind<span class="op">=</span><span class="st">'hist'</span>)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>That looks not super informative. The reason is that by default the plot command only creates 10 bins for the histogram. Plus, as for most online communities, we see a very strong participation inequality, also known as <a href="https://en.wikipedia.org/wiki/1%25_rule">the 1% rule</a>.</p>
<p>Let’s use a logarithmic scale for the y-axis, create 200 instead of 10 bins and disable the scientific notation on the x-axis:</p>
<div id="ce6813fb-61bf-4173-85fb-1689a88a0b34" class="cell" data-execution_count="40">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> df_users[<span class="st">'editCount'</span>].plot(kind<span class="op">=</span><span class="st">'hist'</span>, bins<span class="op">=</span><span class="dv">200</span>,logy<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">10</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>ax.ticklabel_format(style<span class="op">=</span><span class="st">'plain'</span>,axis<span class="op">=</span><span class="st">'x'</span>)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>That already looks more insightful. Es expected, the largest part of our users made compartively few edits, while there’s a few outliers that did a lot of edits.</p>
<p>We can now also split this graph into those users who are bots and those who arent:</p>
<div id="33756eda-60cc-4312-b859-3d682d860e35" class="cell" data-execution_count="197">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df_users <span class="op">=</span> df_users.set_index(<span class="st">'username'</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>df_users.plot.hist(column<span class="op">=</span><span class="st">'editCount'</span>,by<span class="op">=</span><span class="st">'is_bot'</span>,bins<span class="op">=</span><span class="dv">200</span>,logy<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">10</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>df_users <span class="op">=</span> df_users.reset_index()</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-24-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can see that amongst the bots, there are more accounts with very large numbers of edits, as one would expect for automated editing. But: Even among the human editors, there are a few outliers that made between 300,000 and nearly 700,000 edits!</p>
<p>We can now also try to split the graph by the user-provided gender information, after exploring the distribution of responses by users:</p>
<div id="5db855fd-b7f2-4db6-9f46-093ea557af5c" class="cell" data-execution_count="225">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>df_users[<span class="st">'gender'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, xlabel<span class="op">=</span><span class="st">'User-provided gender'</span>, ylabel<span class="op">=</span><span class="st">'Count'</span>)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-25-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We see that the vast majority of users did not specify their gender through the MediaWiki settings. If we focus on the gender breakdown only for the ~3000 users who did specify it, we see that ~15% of users gave their gender as female.</p>
<div id="a65ececf-b144-440a-93e7-7bb23b05b38b" class="cell" data-execution_count="222">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df_users[df_users[<span class="st">'gender'</span>] <span class="op">!=</span> <span class="st">'unknown'</span>][<span class="st">'gender'</span>].value_counts().plot(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    kind<span class="op">=</span><span class="st">'bar'</span>, xlabel<span class="op">=</span><span class="st">'User-provided gender'</span>, ylabel<span class="op">=</span><span class="st">'Count'</span>)</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-26-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can now break down the editing history:</p>
<div id="8017e4bd-af3e-4101-8301-d0c3eeb551e3" class="cell" data-execution_count="224">
<div class="code-copy-outer-scaffold">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>df_users <span class="op">=</span> df_users.set_index(<span class="st">'username'</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>df_users.plot.hist(column<span class="op">=</span><span class="st">'editCount'</span>,by<span class="op">=</span><span class="st">'gender'</span>,bins<span class="op">=</span><span class="dv">200</span>,logy<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">15</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>df_users <span class="op">=</span> df_users.reset_index()</span></code></pre></div>
<button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure"><p><img src="02-pywikibot_files/figure-html/cell-27-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section></section></section><section id="conclusions-summary" class="level2"><h2 class="anchored" data-anchor-id="conclusions-summary">Conclusions &amp; Summary</h2>
<p>We’ve seen how the <em>MediaWiki Actions API</em> can be interfaced with through the <code>pywikibot</code> library to get details about Wikipedia categories, individual pages along with their editing histories and contributors, and about contributors generally.</p>
<p>We have also explored how we can connect all of these to create a simple data set that we can re-use for more in-depth analyses later on.</p>
<p>But, we have also seen that our way of collecting this data maybe is not ideal yet, as our pages that we sourced from the <code>Kenyan politicans</code> page included unexpected pages, such as the <em>Jomo Kenyatta International Airport</em>. In the next bit, we’ll see how we can query Wikidata to find more specific pages, by filtering for the properties of the page subjects (e.g. if they are people or not).</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/citizensandtech\.github\.io\/sicss-wikipedia\/fr");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body>
</html>
